Algoritmo "Q9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ivoneide Duarte
// Data atual  : 01/09/2022
Var
   i, n: inteiro
Inicio

   Escreva ("Informe um número para ver a tabuada: ")
   Leia(n)
   
   para i <- 1 até 10 faca
        Escreval(n, "x", i, "= ", n*i)
   FimPara
   
Fimalgoritmo