Algoritmo "Q4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2022
Var
   i, soma, n: inteiro
Inicio
   soma <- 0

   para i <- 1 até 1000 faça
      soma <- soma + i
   FimPara
   Escreva ("A soma é: ", soma)
Fimalgoritmo