Algoritmo "Q4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2022
Var
   i, s: inteiro
Inicio
   s <- 0

   para i <- 1 até 500 passo 5 faça
        s <- s + i
   FimPara
   Escreva("A soma é: ",s)
Fimalgoritmo