Algoritmo "Q10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ivoneide Duarte
// Data atual  : 01/09/2022
Var
   i, y: inteiro
Inicio

   para i <- 1 até 10 faca
   escreval("Tabuada de ", i)
      para i <- 1 até 10 faca
         Escreval(i, "x", y, "= ", i*y)
      FimPara
       escreval("")
   FimPara

Fimalgoritmo